apiVersion: v1
kind: PersistentVolume
metadata: 
  name: image-registry-pv
spec: 
  capacity: 
    storage: 100Gi
  accessModes:
  - ReadWriteMany 
  nfs: 
    path: /ocpdata/image-registry
    server: 10.68.68.131
  persistentVolumeReclaimPolicy: Retain
  storageClassName: thin



