apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec: 
  identityProviders: 
  - name: ldapidp
    mappingMethod: claim
    type: LDAP 
    ldap: 
      attributes: 
        id: 
        - uidNumber
        email:
        - mail 
        name:
        - displayName 
        preferredUsername: 
        - uid 
      bindDN: "uid=srv.openshift_idm,cn=users,cn=accounts,dc=emea,dc=vcstest,dc=local"
      bindPassword:
        name: ldap-secret
      ca:
        name: ca-config-map
      insecure: false 
      url: "ldaps://uktmimsidm1.emea.vcstest.local:636/dc=emea,dc=vcstest,dc=local?uid?sub?(memberof=cn=ipausers,cn=groups,cn=accounts,dc=emea,dc=vcstest,dc=local)"
